# Generated by Django 2.0.4 on 2018-04-20 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration', models.TextField()),
                ('name', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], max_length=16)),
                ('stage', models.IntegerField(blank=True, default=0)),
                ('stages_number', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='crawltask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_tasks', to='core.Task'),
        ),
    ]
