# Generated by Django 2.0.4 on 2018-04-18 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('random_key', models.CharField(max_length=32)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('configuration', models.TextField()),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='WorkerHost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('is_busy', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='crawltask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crawl_tasks', to='core.Task'),
        ),
        migrations.AddField(
            model_name='crawltask',
            name='worker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crawl_tasks', to='core.WorkerHost'),
        ),
    ]
