# Generated by Django 2.0.4 on 2018-04-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawltask',
            name='stage',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawltask',
            name='tiger_task_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='crawltask',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='waiting', max_length=16),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(blank=True, choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='waiting', max_length=16),
        ),
    ]
