# Generated by Django 2.0.4 on 2018-04-20 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_stage_and_tasktiger_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawltask',
            name='tiger_task_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
