# Generated by Django 2.0.4 on 2018-05-04 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20180420_1838'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subtask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.IntegerField()),
                ('type', models.CharField(choices=[('action', 'Action'), ('crawl', 'Crawl'), ('analysis', 'Analysis')], max_length=16)),
                ('configuration', models.TextField(null=True)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('processing', 'Processing'), ('done', 'Done'), ('error', 'Error')], default='waiting', max_length=16)),
                ('tiger_task_id', models.CharField(max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='crawltask',
            name='parent_task',
        ),
        migrations.AddField(
            model_name='task',
            name='info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CrawlTask',
        ),
        migrations.AddField(
            model_name='subtask',
            name='parent_task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtasks', to='core.Task'),
        ),
    ]
