# Generated by Django 2.0.4 on 2018-05-05 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180504_2007'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subtask',
            name='created_at',
        ),
        migrations.AddField(
            model_name='subtask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
