# Generated by Django 2.0.4 on 2018-05-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180505_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawllink',
            name='url',
        ),
        migrations.AddField(
            model_name='crawllink',
            name='data',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crawllink',
            name='key',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subtask',
            name='type',
            field=models.CharField(choices=[('action', 'Action'), ('crawl', 'Crawl'), ('analysis', 'Analysis'), ('user_input', 'User Input')], max_length=16),
        ),
    ]
