# Generated by Django 2.0.4 on 2018-05-31 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180531_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawllink',
            name='data',
            field=models.BinaryField(),
        ),
    ]
